about/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.about_me, name='about'),
]

bookings/urls.py
from . import views
from django.urls import path
from .views import ReservationCreateView

app_name = "bookings"

urlpatterns = [
    path(
        "new/",
        ReservationCreateView.as_view(),
        name="reservation_new"
    ),
    path("booked-dates/<slug:cottage_slug>/",
         views.booked_dates_json,
         name="booked_dates_json")
]

cottages/urls.py
from django.urls import path
from .views import (
    HomePageView,
    cottage_detail,
    review_edit,
    review_delete,
    review_detail,
)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('reviews/', review_detail, name='review_detail'),
    path('<slug:slug>/', cottage_detail, name='cottage_detail'),
    path('<slug:slug>/edit_review/<slug:review_slug>/',
         review_edit,
         name='review_edit'),
    path('<slug:slug>/delete_review/<slug:review_slug>/',
         review_delete,
         name='review_delete'),
]

happy_valley_holidays/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("about/", include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('password_change/', 
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), 
         name='password_change'),

    path('password_change/done/', 
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
         name='password_change_done'),
    path("", include("cottages.urls"), name="cottages-urls"),
    path("bookings/", include(("bookings.urls", "bookings"), namespace="bookings")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cottages/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# from cloudinary.models import CloudinaryField
from django.utils import timezone
import itertools


STATUS = ((0, "Draft"), (1, "Published"))


# cottage model
class Cottage(models.Model):

    cottage_id = models.CharField(
        primary_key=True,
        max_length=20,
        unique=True,
        blank=False,
        null=False,
    )
    featured_image = models.ImageField(
        upload_to='cottages/featured',
        blank=True,
        null=True,
        default='placeholder'
    )
    description = models.CharField(
        max_length=400,
        blank=True,
        null=True,
        default="Untitled Cottage"
    )
    slug = models.SlugField(max_length=200, blank=True)
    bedrooms = models.IntegerField()
    bathrooms = models.IntegerField()
    max_guests = models.IntegerField()
    price_per_night = models.DecimalField(max_digits=10, decimal_places=2)
    # pretty name for pulldown menu on cottage page

    @property
    def pretty_name(self):
        return self.slug.replace('-', ' ').title()

    def image_url(self):
        if self.featured_image:
            return self.featured_image.url
        return ''

    def __str__(self):
        return f"{self.cottage_id} Cottage"


# Unique slug generation for the Cottage model
def unique_slugify(instance, slug_field, slug_source):
    slug = slugify(slug_source)
    ModelClass = instance.__class__
    unique_slug = slug
    for i in itertools.count(1):
        if not ModelClass.objects.filter(**{slug_field: unique_slug}).exists():
            break
        unique_slug = f"{slug}-{i}"
    setattr(instance, slug_field, unique_slug)


# cottage image model
class CottageImage(models.Model):
    cottage = models.ForeignKey(
        Cottage,
        related_name='images',
        on_delete=models.CASCADE
    )
    image = models.ImageField(
        upload_to='cottages/images',
        blank=True,
        null=True,
        default='placeholder'
    )
    caption = models.CharField(max_length=255, blank=True)
    import_batch_id = models.CharField(max_length=100, blank=True, null=True)


# Image model for hero carousel
class HeroImage(models.Model):
    image = models.ImageField(upload_to='cottages/hero', blank=True, null=True,
                              default='placeholder')
    caption = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.caption or self.image.name


# Review model for cottages
class Review(models.Model):
    review_id = models.AutoField(primary_key=True)
    guest = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="reviewer")
    cottage = models.ForeignKey(
        Cottage, on_delete=models.CASCADE, related_name="reviews")
    title = models.CharField(max_length=120)
    featured_image = models.ImageField(
        upload_to='cottages/featured', blank=True, null=True,
        default='placeholder')
    rating = models.IntegerField(
        default=0,
        choices=[(i, str(i)) for i in range(1, 6)],
        blank=True,
        null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    body = models.TextField(max_length=200)
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(default=timezone.now)

    # Unique slug generation for the Review model
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            slug = base_slug
            counter = 1
            while Review.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Review by {self.guest} on {self.cottage}"

    class Meta:
        unique_together = ('guest', 'cottage', "created_on")
        ordering = ["created_on"]

cottages/forms.py
from .models import Review, Cottage
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'body', 'rating', 'featured_image')

        widgets = {
            'title': forms.Textarea(attrs={
                'placeholder': 'Write your title here...',
                'rows': 1,
                'class': 'form-control'
            }),
            'body': forms.Textarea(attrs={
                'placeholder': 'Write your review here...',
                'rows': 10,
                'class': 'form-control'
            })
        }

cottages/views.py
import os
from .models import Cottage, Review, HeroImage
from .forms import ReviewForm
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.urls import reverse
from django.db.models import Q


# home page view
class HomePageView(TemplateView):
    template_name = "cottages/index.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context["cottage_list"] = Cottage.objects.all()
        context["review_list"] = Review.objects.all()

        # Filter and order reviews
        review_qs = Review.objects.filter(
            approved=True
        ).order_by(
            '-rating', '-created_at'
        )
        paginator = Paginator(review_qs, 3)

        # Handle pagination
        page = self.request.GET.get("page")
        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        # Add paginated reviews to context
        context["review_list"] = page_obj.object_list
        context["page_obj"] = page_obj
        context["is_paginated"] = page_obj.has_other_pages()

        context["lake_images"] = HeroImage.objects.filter(image__isnull=False).exclude(image='').order_by('image')

        return context


# Cottage detail view
def cottage_detail(request, slug):
    cottage = get_object_or_404(Cottage, slug=slug)
    images = cottage.images.all().order_by('image')
    cottages = Cottage.objects.all()

    # Filter and order reviews
    reviews_qs = cottage.reviews.filter(
        approved=True
    ).order_by("-created_on")
    review_count = reviews_qs.count()

    # Set up pagination
    paginator = Paginator(reviews_qs, 1)
    page = request.GET.get("page")
    page_obj = paginator.get_page(page)

    # Handle review form
    if request.method == "POST":
        review_form = ReviewForm(data=request.POST, files=request.FILES)
        if review_form.is_valid():
            review = review_form.save(
                commit=False
            )
            review.guest = request.user
            review.cottage = cottage
            review.save()

    else:
        review_form = ReviewForm()

    context = {
        'cottage': cottage,
        'cottages': cottages,
        'images': images,
        'reviews': page_obj,
        'page_obj': page_obj,
        'is_paginated': page_obj.has_other_pages(),
        'review_count': review_count,
        'review_form': review_form,
    }

    return render(request, 'cottages/cottage_detail.html', context)


# Review detail view
def review_detail(request):
    cottages = ['rock-terrace', 'pen-y-graig']
    paginated_reviews_by_cottage = {}
    # Get all cottages to paginate reviews
    for slug in cottages:
        cottage = get_object_or_404(Cottage, slug=slug)
        reviews_qs = (
            Review.objects.filter(cottage=cottage, approved=True)
            .order_by('-rating', '-created_at')
        )
        paginator = Paginator(reviews_qs, 3)
        page_number = request.GET.get(f'page_{slug}')
        page_obj = paginator.get_page(page_number)
        paginated_reviews_by_cottage[cottage] = page_obj
    # Handle review submission
    if request.method == "POST":
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.guest = request.user
            review.save()
            messages.success(
                request,
                'Review submitted and awaiting approval.'
            )
            return HttpResponseRedirect(request.path_info)
    else:
        review_form = ReviewForm()
    # Render the template with paginated reviews and review form
    return render(request, 'cottages/review_detail.html', {
        'paginated_reviews_by_cottage': paginated_reviews_by_cottage,
        'review_form': review_form,
    })


# Review edit and delete views
def review_edit(request, slug, review_slug):
    review = get_object_or_404(Review, slug=review_slug, guest=request.user)
    # Handle review submission
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.approved = False  # Reset approval on edit
            review.save()
            messages.info(
                request,
                "Your edited review is now awaiting approval."
            )
            return redirect('cottage_detail', slug=slug)
    else:
        form = ReviewForm(instance=review)
    # Render the edit form
    return render(request, 'review_edit.html', {'form': form})


# Review delete view
def review_delete(request, slug, review_slug):
    review = get_object_or_404(Review, slug=review_slug, cottage__slug=slug)
    # Check if the user is the guest who wrote the review
    if review.guest == request.user:
        review.delete()
        messages.success(request, 'Review deleted!')
    else:
        messages.error(request, 'You can only delete your own review!')
    # Redirect to the cottage detail page
    return HttpResponseRedirect(reverse('cottage_detail', args=[slug]))

cottages/templates/cottages/#review_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div id="reviews-section" class="container col-12 mt-1">
  <!-- reviews paginated by 3  by cottage -->
  {% for cottage, page_obj in paginated_reviews_by_cottage.items %}
    <div class="row mb-2">
      <div class="col-12">
        <h2 class="text-center text-capitalize my-4">{{ cottage.cottage_id }} Reviews</h2>
      </div>
    </div>

    <div class="row">
      {% for review in page_obj.object_list %}
        <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body">
                <!-- custom css -->
                <h4 class="truncate-one-line d-block fs-5 fs-md-6"
                style="max-width: 100%; width: 100%;"
                >{{ review.title }}
                </h4>
                {% if review.featured_image %}
                  <img src="{{ review.featured_image.url }}" alt="Review Image" class="img-fluid"/>
                {% endif %}
                <div>
                  {{ review.body | linebreaks }}
                </div>
                  <p class="card-text">Rating: {{ review.rating }}/5</p>
                  <p><span class="font-weight-normal">{{ review.created_on }}</span></p>
              </div>
            </div>
        </div>
      {% endfor %}
    </div>
    <!-- Pagination controls per cottage -->
    <div class="d-flex justify-content-between my-3">
    <!-- Next button condition -->
    {% if page_obj.has_previous %}
      <a href="?page_{{ cottage.slug }}={{ page_obj.previous_page_number }}" class="btn btn-outline-dark">
        &#8592; Previous 3 Reviews
      </a>
    {% else %}
    <!-- Keeps spacing consistent if no previous page -->
      <span></span>
    {% endif %}
    <!-- Next button condition -->
    {% if page_obj.has_next %}
      <a href="?page_{{ cottage.slug }}={{ page_obj.next_page_number }}" class="btn btn-dark">
        Next 3 Reviews &#8594;
      </a>
    {% endif %}
  </div>
  {% endfor %}
</div>
  <!-- End of reviews section -->
{% endblock %}

cottages/templates/cottages/cottage_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">

  <!-- Pulldown menu -->
    <div class="d-flex justify-content-center mb-4">
      <div class="dropdown">
        <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="cottageDropdown"
            data-bs-toggle="dropdown" aria-expanded="false">
            {{ cottage.pretty_name }} 
        </button>
        <ul class="dropdown-menu" aria-labelledby="cottageDropdown">
            {% for c in cottages %}
                <li>
                    <a class="dropdown-item" href="{% url 'cottage_detail' c.slug %}">
                      {{ c.pretty_name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
      </div>
    </div>
    <!-- Cottage Details Card -->
    <!-- Cottage Image Carousel -->
    <div class="card mb-4">
        <div id="cottageCarousel" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <!--  for loop to hide img captions on smaller screens  -->
            {% for img in images %}
              <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <img src="{{ img.image.url }}" class="d-block w-100" alt="{{ img.caption|default:cottage.pretty_name }}">
                {% if img.caption %}
                <div class="carousel-caption d-none d-md-block">
                  <p>{{ img.caption }}</p>
                </div>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          <!-- Carousel controls -->
          <button class="carousel-control-prev" type="button" data-bs-target="#cottageCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#cottageCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <!-- cottages -->
        <div class="card-body">
            <h2 class="card-title" id="description">{{ cottage.id }}</h2>
            <p class="card-text">{{ cottage.description }}</p>
            <hr>
            <h4 id="features">Features</h4>
            <ul>
                {% if cottage.bedrooms %}<li>Bedrooms: {{ cottage.bedrooms }} Bathrooms: {{ cottage.bathrooms }}</li>{% endif %}
                {% if cottage.price_per_night %}<li>Price per night: £{{ cottage.price_per_night }}</li>{% endif %}
            </ul>
            <hr>
            <!-- Booking form -->
            <div class="text-center">
                  <a href="{% url 'bookings:reservation_new' %}?cottage={{ cottage.slug }}" class="btn btn-primary">
                    Book Now!
                  </a>
            </div>
        </div>
    </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <!-- Displaying count of reviews -->
      <strong class="text-secondary">
        <i class="far fa-comments"></i> {{ review_count }}
      </strong>
    </div>
  </div>
  <!-- Displaying Reviews -->
  <div class="row">
    <div id="reviews-section" class="col-md-8 card mb-4  mt-3 ">
      <h3>Reviews:</h3>
      <div class="card-body">
        <!-- for loop to assess the paginated (by one) reviews permissions -->
        {% for review in page_obj %}
          <div class="p-2 reviews
            {% if not review.approved and review.guest == user %}
              faded
            {% elif not review.approved %}
              d-none
            {% endif %}
          ">
        <p class="font-weight-bold">
          {{ review.guest }}
          <span class="font-weight-normal">{{ review.created_on }}</span> wrote:
        </p>
        <!-- display title on one line - custom css -->
        <h4 class="truncate-one-line d-block fs-5 fs-md-6" style="max-width: 100%; width: 100%;">{{ review.title }}</h4>
        {% if review.featured_image %}
        <!-- display image - custom css -->
          <img src="{{ review.featured_image.url }}" alt="Review Image" id="review-image" class="img-fluid" />
        {% endif %}
        <div id="review{{ review.slug }}">
          {{ review.body | linebreaks }}
        </div>
        <!-- review permissions -->
        {% if not review.approved and review.guest == user %}
          <p class="approval">This review is awaiting approval</p>
        {% endif %}
        <!-- review delete and edit permissions -->
        {% if user.is_authenticated and review.guest == user %}
        <!-- use slug of review title to identify review -->
            <button class="btn btn-delete" 
          data-url="{% url 'review_delete' slug=cottage.slug review_slug=review.slug %}">
            Delete
          </button>
        <!-- use slug of review title to identify review -->
          <button class="btn btn-edit" data-review-slug="{{ review.slug }}">Edit</button>
        {% endif %}
        </div>
        <!-- end of review -->
        <hr>
        <!-- review pagination buttons -->
        {% if is_paginated %}
          <div class="d-flex justify-content-between my-4">
            <!-- previous button condition custom css -->
            {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}#reviews-section" class="btn btn-outline-dark btn-lg">
                &laquo; Previous Review
              </a>
            {% else %}
              <span></span>
            {% endif %}
            <!-- next button condition custom css -->
            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}#reviews-section" class="btn btn-dark btn-lg">
                Next Review &raquo;
              </a>
            {% endif %}
          </div>
        {% endif %}
        {% endfor %}
        <!-- Our for loop ends here -->
      </div>
    </div>
    <!-- Creating New Reviews -->
    <div class="col-md-4 card mb-4 mt-3">
      <div class="card-body">
        <!-- new review permissions -->
        {% if user.is_authenticated %}
          <h3>Leave a review:</h3>
          <p>Posting as: {{ user.username }}</p>
          <!-- create slug of review title to identify review -->
          <form id="reviewForm"
            method="post"
            enctype="multipart/form-data"
            data-slug="{{ cottage.slug }}"
            style="margin-top: 1.3em;">
            {{ review_form | crispy }}
            {% csrf_token %}
            <button id="submitButton" type="submit"
              class="btn btn-signup btn-lg">Submit</button>
          </form>
        {% else %}
          <p>Log in to leave a review</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
  aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete review?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your review?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block extras %}
<script src="{% static 'js/reviews.js' %}"></script>
{% endblock %}

cottages/templates/cottages/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- index.html content starts here -->
<!-- hero image carousel - custom css -->
<div class="col-12 mt-3 left">
  <div class="row">
      <h1 class="card-header text-center">
        <strong>Lake Forest Town</strong>
      </h1>
      {% if lake_images %}
      <div id="heroCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          {% for img in lake_images %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <img
              src="{{ img.image.url }}"
              class="d-block w-100"
              alt="{{ img.caption }}"
            />
          </div>
          {% endfor %}
        </div>
        <!-- carousel navigation -->
        <button
          class="carousel-control-prev"
          type="button"
          data-bs-target="#heroCarousel"
          data-bs-slide="prev"
          aria-label="Previous slide"
          title="Previous slide"
        >
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </button>
        <button
          class="carousel-control-next"
          type="button"
          data-bs-target="#heroCarousel"
          data-bs-slide="next"
          aria-label="Next slide"
          title="Next slide"
        >
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </button>
      </div>
      {% endif %}
  </div>
</div>
      <!-- Cottages -->
      <div class="col-12 mt-3 left">
        <div class="row">
          <h1 class="card-header text-center">
            <strong>Cottages</strong>
          </h1>
          {% for cottage in cottage_list %}
          <div class="col-md-6">
            <div class="card mb-6">
              <div class="card-body">
                <div class="image-container">
                  {% if cottage.featured_image %}
                    <img class="card-img-top" src="{{ cottage.featured_image.url }}" alt="{{ cottage.cottage_id }}">
                  {% else %}
                    <p>No image available for {{ cottage.pretty_name }}</p>
                  {% endif %}
                  <div class="image-flash"></div>
                </div>
                <!-- link to cottage detail template -->
                <a
                  href="{% url 'cottage_detail' cottage.slug %}"
                  class="post-link"
                >
                  <h2 class="card-title">{{ cottage.cottage_id }}</h2>
                </a>
                <p class="card-text">{{ cottage.description }}</p>
                <hr />
                <p class="card-text text-muted h6">
                  Price per night: £{{ cottage.price_per_night }}
                </p>
                <hr />
                <div class="card-text text-muted h6">
                  <a href="{% url 'bookings:reservation_new' %}?cottage={{ cottage.slug }}" class="btn btn-signup">
                    Book Now!
                  </a>
                </div>
              </div>
            </div>
          </div>
          <!-- cottages paginated by 2 -->
          {% if forloop.counter|divisibleby:2 %}
        </div>
        <div class="row">
          {% endif %}
          {% endfor %}
        </div>
      </div>
    <div class="row">
      <!-- Reviews Column -->
      <div class="col-12 mt-3 justify-content-center">
        <div class="row">
          <h2 class="text-center">
            Reviews
          </h2>
          <!-- reviews paginated by 3 -->
          {% for review in review_list %}
          <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body">
                <h2
                  class="truncate-one-line d-block fs-5 fs-md-6 review-title"
                >
                  {{ review.title }}
                </h2>
                <div class="image-container">
                  {% if "placeholder" in review.featured_image.url %}
                  <img
                    class="img-fluid"
                    src="{% static 'images/default.jpg' %}"
                    alt="placeholder image"
                  />
                  {% else %}
                  <img
                    class="img-fluid"
                    src="{{ review.featured_image.url }}"
                    alt="{{ review.title }}"
                  />
                  {% endif %}
                </div>
                <p class="card-text">Rating: {{ review.rating }}/5</p>
                <p class="card-text text-muted h6">{{ review.created_at}}</p>
                <hr />
              </div>
            </div>
          </div>
          {% if forloop.counter|divisibleby:3 %}
        </div>
        <div class="row">
          {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
    {% if is_paginated %}
    <!-- condition to display previous button -->
    <div class="d-flex justify-content-between align-items-center mb-4">
      {% if page_obj.has_previous %}
      <a
        href="?page={{ page_obj.previous_page_number }}#reviews-section"
        class="btn btn-outline-dark btn-lg"
      >
        &laquo; Previous 3 Reviews
      </a>
      {% else %}
      <!-- Keeps spacing consistent if no previous page -->
      <span></span>
       <!-- condition to display next button -->
      {% endif %} {% if page_obj.has_next %}
      <a
        href="?page={{ page_obj.next_page_number }}#reviews-section"
        class="btn btn-dark btn-lg"
      >
        Next 3 Reviews &raquo;
      </a>
      {% endif %}
    </div>
    {% endif %}
  {% endblock %}
<!-- index.html content ends here -->

cottages/templates/cottages/review_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div id="reviews-section" class="container col-12 mt-1">
  <!-- reviews paginated by 3  by cottage -->
  {% for cottage, page_obj in paginated_reviews_by_cottage.items %}
    <div class="row mb-2">
      <div class="col-12">
        <h2 class="text-center text-capitalize my-4">{{ cottage.cottage_id }} Reviews</h2>
      </div>
    </div>

    <div class="row">
      {% for review in page_obj.object_list %}
        <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body">
                <!-- custom css -->
                <h4 class="truncate-one-line d-block fs-5 fs-md-6"
                style="max-width: 100%; width: 100%;"
                >{{ review.title }}
                </h4>
                {% if review.featured_image %}
                  <img src="{{ review.featured_image.url }}" alt="Review Image" class="img-fluid"/>
                {% endif %}
                <div>
                  {{ review.body | linebreaks }}
                </div>
                  <p class="card-text">Rating: {{ review.rating }}/5</p>
                  <p><span class="font-weight-normal">{{ review.created_on }}</span></p>
              </div>
            </div>
        </div>
      {% endfor %}
    </div>
    <!-- Pagination controls per cottage -->
    <div class="d-flex justify-content-between my-3">
    <!-- Next button condition -->
    {% if page_obj.has_previous %}
      <a href="?page_{{ cottage.slug }}={{ page_obj.previous_page_number }}" class="btn btn-outline-dark">
        &#8592; Previous 3 Reviews
      </a>
    {% else %}
    <!-- Keeps spacing consistent if no previous page -->
      <span></span>
    {% endif %}
    <!-- Next button condition -->
    {% if page_obj.has_next %}
      <a href="?page_{{ cottage.slug }}={{ page_obj.next_page_number }}" class="btn btn-dark">
        Next 3 Reviews &#8594;
      </a>
    {% endif %}
  </div>
  {% endfor %}
</div>
  <!-- End of reviews section -->
{% endblock %}